[package]
name = "js_executor"
authors.workspace = true
#edition.workspace = true
edition = "2024"
rust-version.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"


[dependencies]
deno_core = { workspace = true }
