[workspace]
resolver = "3"
members = ["cli/*", "crates/*"]
# default-members = ["cli/omni"]

[workspace.package]
homepage = "https://github.com/omni-build/omni"
license = "MIT"
repository = "https://github.com/omni-build/omni"
keywords = ["build", "build-system", "build-tools", "cli", "omni", "devops"]
readme = "README.md"
documentation = "https://docs.rs/omni"
description = "A build system for the modern age"
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils",
]
rust-version = "1.88.0"
edition = "2024"
version = "0.0.0-semantically-released"
authors = ["Clarence Manuel <rencedm112@gmail.com>"]

[workspace.dependencies]
serde = { version = "^1.0.219", features = ["derive", "rc", "alloc"] }
sys_traits = { version = "^0.1.16", features = ["real"] }
system_traits = { path = "./crates/system_traits" }
async-trait = { version = "^0.1.88" }
serde_json = { version = "^1.0.140" }
trace = { path = "./crates/trace" }
tracing = { version = "^0.1.41" }
tracing-log = { version = "^0.2.0" }
tracing-subscriber = { version = "^0.3.19" }
tracing-serde = { version = "^0.2.0" }
futures = { version = "^0.3.31" }
thiserror = "^2.0.12"
eyre = "^0.6.12"
time = { version = "^0.3.41", features = [] }
derive_more = { version = "^2.0.1", features = ["full"] }
strum = { version = "^0.27.1", features = ["derive"] }
tokio = { version = "^1.46.1", features = [
    "rt",
    "rt-multi-thread",
    "tracing",
    "sync",
    "fs",
    "net",
    "socket2",
    "time",
    "macros",
    "process",
] }
tokio-util = { version = "^0.7.15" }
itertools = { version = "^0.14.0" }
rayon = { version = "^1.10.0" }
reqwest = { version = "^0.12.15", features = [
    "charset",
    "blocking",
    "rustls-tls",
    "http2",
], default-features = false }
# deno_core = { version = "^0.351.0" }
# deno_core = { version = "^0.352.0" }
http = { version = "^1.3.1" }
http-body = { version = "^1.0.1" }
http-body-util = { version = "^0.1.3" }
percent-encoding = { version = "^2.3.1" }
clap = { version = "^4.5.38", features = ["derive", "env"] }
clap_complete = { version = "^4.5.50" }
globset = { version = "^0.4" }
shadow-rs = { version = "^1.1.1", default-features = false }
convert_case = { version = "^0.8.0" }
schemars = { version = "^1.0.0" }
walkdir = { version = "^2.5.0" }
serde_yml = { version = "^0.0.12" }
ignore = { version = "^0.4.23" }
regex = { version = "^1.11.1" }
lazy-regex = { version = "^3.4.1" }
env = { path = "./crates/env" }
env_loader = { path = "./crates/env_loader" }
petgraph = { version = "^0.8.2" }
omni_core = { path = "./crates/omni_core" }
config_utils = { path = "./crates/config_utils" }
js_runtime = { path = "./crates/js_runtime" }
toml = { version = "^0.9.0" }
uuid = { version = "^1.17.0", features = ["v4", "v7"] }
url = { version = "^2.5.4" }
parking_lot = { version = "^0.12.4" }
bincode = { version = "^2.0.1", features = ["serde"] }
notify = { version = "^8.0.0" }
dir_walker = { path = "./crates/dir_walker" }
deno_task_shell = { version = "^0.25.1" }

[profile.release]
incremental = true
opt-level = 3       # optimize for speed but increase binary size
codegen-units = 1   # less parallel compilation but more optimization can be done
lto = true          # can perform faster but slower compilation
strip = "debuginfo" # strip debug info from binary to reduce binary size
#debug = false
debug = "line-tables-only"
debug-assertions = false
overflow-checks = false
split-debuginfo = "packed"

# Build release with debug symbols: cargo build --profile=release-with-debug
[profile.release-with-debug]
inherits = "release"
debug = true

# Faster to compile than `release` but with similar performance.
[profile.release-lite]
inherits = "release"
codegen-units = 128
lto = "thin"

# Key generation is too slow on `debug`
# [profile.dev.package.num-bigint-dig]
# opt-level = 3

# rusty-v8 needs at least -O1 to not miscompile
# [profile.dev.package.v8]
# opt-level = 1

# [profile.release.package.async-compression]
# opt-level = 3
# [profile.release.package.base64-simd]
# opt-level = 3
# [profile.release.package.brotli]
# opt-level = 3
# [profile.release.package.brotli-decompressor]
# opt-level = 3
# [profile.release.package.bytes]
# opt-level = 3
# [profile.release.package.deno_broadcast_channel]
# opt-level = 3
# [profile.release.package.deno_core]
# opt-level = 3
# [profile.release.package.deno_crypto]
# opt-level = 3
# [profile.release.package.deno_fetch]
# opt-level = 3
# [profile.release.package.deno_ffi]
# opt-level = 3
# [profile.release.package.deno_http]
# opt-level = 3
# [profile.release.package.deno_net]
# opt-level = 3
# [profile.release.package.deno_node]
# opt-level = 3
# [profile.release.package.deno_runtime]
# opt-level = 3
# [profile.release.package.deno_tls]
# opt-level = 3
# [profile.release.package.deno_url]
# opt-level = 3
# [profile.release.package.deno_web]
# opt-level = 3
# [profile.release.package.deno_websocket]
# opt-level = 3
# [profile.release.package.fastwebsockets]
# opt-level = 3
# [profile.release.package.flate2]
# opt-level = 3
# [profile.release.package.futures-util]
# opt-level = 3
# [profile.release.package.futures-io]
# opt-level = 3
# [profile.release.package.futures-channel]
# opt-level = 3
# [profile.release.package.futures-sink]
# opt-level = 3
# [profile.release.package.futures-task]
# opt-level = 3
# [profile.release.package.futures-core]
# opt-level = 3
# [profile.release.package.hyper]
# opt-level = 3
# [profile.release.package.miniz_oxide]
# opt-level = 3
# [profile.release.package.num-bigint-dig]
# opt-level = 3
# [profile.release.package.rand]
# opt-level = 3
# [profile.release.package.serde]
# opt-level = 3
# [profile.release.package.serde_v8]
# opt-level = 3
# [profile.release.package.tokio]
# opt-level = 3
# [profile.release.package.url]
# opt-level = 3
# [profile.release.package.v8]
# opt-level = 3
# [profile.release.package.http]
# opt-level = 3
# [profile.release.package.http-body]
# opt-level = 3
# [profile.release.package.httparse]
# opt-level = 3
# [profile.release.package.mio]
# opt-level = 3
# [profile.release.package.fnv]
# opt-level = 3
# [profile.release.package.hyper-util]
# opt-level = 3
# [profile.release.package.httpdate]
# opt-level = 3
# [profile.release.package.deno_unsync]
# opt-level = 3
# [profile.release.package.deno_semver]
# opt-level = 3
# [profile.release.package.deno_npm]
# opt-level = 3
# [profile.release.package.deno_lockfile]
# opt-level = 3
