[workspace]
resolver = "3"
members = ["cli/*", "crates/*"]
default-members = ["cli/omni"]

[workspace.package]
rust-version = "1.89.0"
edition = "2024"
version = "0.0.0-semantically-released"
authors = ["Clarence Manuel <rencedm112@gmail.com>"]

[profile.release]
opt-level = 3            # optimize for speed but increase binary size
codegen-units = 1        # less parallel compilation but more optimization can be done
lto = true               # can perform faster but slower compilation
strip = "debuginfo"      # strip debug info from binary to reduce binary size
debug = false
debug-assertions = false
overflow-checks = false

[profile.dev]

[workspace.dependencies]
serde = { version = "^1.0.219", features = ["derive", "rc", "alloc"] }
serde_json = "^1.0.140"
tracing = "^0.1.41"
tracing-subscriber = "^0.3.19"
thiserror = "^2.0.12"
eyre = "^0.6.12"
time = { version = "^0.3.41", features = [] }
derive_more = { version = "^2.0.1", features = ["full"] }
strum = { version = "^0.27.1", features = ["derive"] }
tokio = { version = "^1.45.0", features = [
    "rt",
    "rt-multi-thread",
    "tracing",
    "sync",
    "fs",
    "net",
    "socket2",
    "time",
    "macros",
] }
itertools = { version = "^0.14.0" }
rayon = { version = "^1.10.0" }
reqwest = { version = "^0.12.15", features = [
    "charset",
    "blocking",
    "rustls-tls",
    "http2",
], default-features = false }
deno_core = { version = "^0.347.0" }
oxc = { version = "*", features = ["full"] }
clap = { version = "^4.5.38", features = ["derive", "env"] }
clap_complete = { version = "^4.5.50" }
globset = { version = "^0.4" }
shadow-rs = { version = "^1.1.1", default-features = false }
convert_case = { version = "^0.8.0" }
schemars = { version = "0.8.22" }
walkdir = { version = "2.5.0" }
serde_yml = { version = "0.0.12" }
ignore = { version = "0.4.23" }
regex = { version = "1.11.1" }
env = { path = "./crates/env" }
env_loader = { path = "./crates/env_loader" }
petgraph = { version = "^0.8.1" }
omni_core = { path = "./crates/omni_core" }
