[package]
name = "omni"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
deno_core = { workspace = true }
oxc = { workspace = true }
eyre = { workspace = true }
color-eyre = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
clap_complete = { workspace = true }
shadow-rs = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
env_loader = { path = "../../crates/env_loader" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yml = { workspace = true }
schemars = { workspace = true }
walkdir = { workspace = true }
globset = { workspace = true }
ignore = { workspace = true }
regex = { workspace = true }


[build-dependencies]
shadow-rs = { workspace = true, features = ["default"] }
eyre = { workspace = true }
