[package]
name = "omni"
rust-version.workspace = true
edition.workspace = true
# edition = "2024"
version.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = ["enable-tracing"]
enable-tracing = ["trace/enabled", "dep:tracing", "dep:tracing-subscriber"]

[dependencies]
#oxc = { workspace = true }
eyre = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
clap_complete = { workspace = true }
shadow-rs = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
trace = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
env_loader = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yml = { workspace = true }
schemars = { workspace = true }
globset = { workspace = true }
regex = { workspace = true }
lazy-regex = { workspace = true }
omni_core = { workspace = true }
config_utils = { workspace = true, features = ["serde", "schemars", "merge"] }
merge = { workspace = true }
toml = { workspace = true }
js_runtime = { workspace = true }
system_traits = { workspace = true, features = [
    "real-async-tokio",
    "real-sync",
] }
dir_walker = { workspace = true, features = ["ignore", "memory"] }
tracing-log = { workspace = true }
deno_task_shell = { workspace = true }
petgraph = { workspace = true }
thiserror = { workspace = true }
defer = { workspace = true }

[build-dependencies]
shadow-rs = { workspace = true, features = ["default"] }
eyre = { workspace = true }
